lang: c
os: linux
dist: trusty
root: true

before_install:
  - sudo add-apt-repository -y ppa:gnome3-team/gnome3
  - sudo add-apt-repository -y ppa:gnome3-team/gnome3-staging
  - sudo add-apt-repository -y ppa:vala-team/ppa
  - sudo add-apt-repository -y ppa:ricotz/testing
  - sudo apt-get update
  - sudo apt-get install -y libgtk-3-dev libxml2-utils librest-dev libjson-glib-dev libsqlite3-dev libsoup2.4-dev intltool libgee-dev valac libglib2.0-dev automake libgee-dev autopoint

script:
  - sed -i -e 's|0.19.7|0.17|g' configure.ac # Fix "Please upgrade to gettext-0.19.7 or newer."
  - sed -i -e 's| >= 0.7.93||g' configure.ac # Revert 2bca4d19db915c13c05a957ad73bd5508d8fc747
  - sed -i -e 's| >= 3.18||g' configure.ac # Fix "Requested 'gtk+-3.0 >= 3.18' but version of GTK+ is 3.14.15
  - sed -i -e 's| >= 2.44||g' configure.ac # Fix "Requested 'glib-2.0 >= 2.44' but version of GLib is 2.42.2
  - ./autogen.sh --prefix=/app --disable-video --disable_gst_check
  - make
  - sudo make install
  - find /app
